services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8087:80"
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      CLEAR_CACHE_ON_START: "false"
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - laravel-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-scheduler
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    depends_on:
      - mysql
      - app
      - rabbitmq
    networks:
      - laravel-network
    command: >
      sh -c "while true; do
               php artisan schedule:run --verbose --no-interaction >> /var/www/html/storage/logs/scheduler.log 2>&1;
               sleep 60;
             done"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    depends_on:
      - mysql
      - app
      - rabbitmq
    networks:
      - laravel-network
    command: php artisan queue:work --verbose --tries=3 --timeout=90

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-1
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: mysql-1
    restart: unless-stopped
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: estoque
      MYSQL_USER: estoque_user
      MYSQL_PASSWORD: teste37
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  db_data:
  vendor_data:

networks:
  laravel-network: